[package]
name = "common-metrics"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[dependencies]
# Workspace dependencies
common-exception = { path = "../exception" }
common-tracing = { path = "../tracing" }

# Crates.io dependencies
metrics = "0.19.0"
metrics-exporter-prometheus = { version = "0.10.0", default-features = false }
once_cell = "1.12.0"
parking_lot = "0.12.1"
prometheus-parse = "0.2.3"
serde = { version = "1.0.137", features = ["derive"] }

[dev-dependencies.tokio]
default-features = false
features = ["io-util", "net", "sync", "rt-multi-thread", "macros"]
version = "1.19.2"
