[package]
name = "common-meta-grpc"
version = "0.1.0"
description = "common meta grpc"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false
test = false

[dependencies]
common-arrow = { path = "../../arrow" }
common-base = { path = "../../base" }
common-exception = { path = "../../exception" }
common-grpc = { path = "../../grpc" }
common-meta-api = { path = "../api" }
common-meta-app = { path = "../app" }
common-meta-types = { path = "../types" }
common-metrics = { path = "../../metrics" }
common-proto-conv = { path = "../../proto-conv" }
common-protos = { path = "../../protos" }
common-tracing = { path = "../../tracing" }

derive_more = "0.99.17"
futures = "0.3.21"
once_cell = "1.12.0"
parking_lot = "0.12.1"
prost = "0.10.4"
rand = "0.8.5"
semver = "1.0.10"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
thiserror = "1.0.31"
tonic = { version = "0.7.2", features = ["transport", "codegen", "prost", "tls-roots", "tls"] }
tracing = "0.1.35"

[dev-dependencies]

[build-dependencies]
common-building = { path = "../../building" }
