queue_rules:
  - name: shared_queue
    conditions:
      - "#approved-reviews-by>=2"

      # Must write expected checks explicitly
      # Reference: https://docs.mergify.com/conditions/#validating-all-status-checks
      # We only require linux checks to pass
      - check-success=check
      - check-success~=^build_(aarch64|x86_64)_musl$
      - check-success=test_unit
      - check-success=test_metactl
      - check-success=test_stateless_standalone_linux
      - check-success=test_stateless_cluster_linux
      - check-success=test_stateful_standalone_linux
      - check-success~=^test_sqllogic_(base|ydb)_standalone_linux$

  - name: docs_queue
    conditions:
      - "#approved-reviews-by>=1"

      # Docs queue only requires Vercel passing.
      - check-success=Vercel

pull_request_rules:
  # Push PR into queue when it passes all checks
  - name: Put into shared queue
    conditions:
      - "#approved-reviews-by>=2"
      - -draft
      - label!=pr-doc
    actions:
      queue:
        name: shared_queue

  # Push docs PR into docs queue
  - name: Put into docs queue
    conditions:
      - "#approved-reviews-by>=1"
      - -draft
      - label=pr-doc
      - check-success=Vercel
    actions:
      queue:
        name: docs_queue

  # Check if PR has conflicts for merging
  - name: Check PR conflicts
    conditions:
      - -conflict
    actions:
      post_check:
        title: |
          {% if check_succeed %}
          PR doesn't have conflicts
          {% else %}
          PR has conflicts
          {% endif %}
        summary: |
          {% if not check_succeed %}
          Pull request has merge conflicts that must be resolved before it can be merged, please update it 🙏.
          {% endif %}

  # Check if PR description contains CLA
  - name: Check PR description
    conditions:
      - author!=Mergify
      - -draft
      - '-body~=I hereby agree to the terms of the CLA available at: https:\/\/databend\.rs\/dev\/policies\/cla\/'
      - "-body~=Summary"
    actions:
      comment:
        message: |
          This pull request's description is not fulfill the requirements. @{{author}} please update it 🙏.

          The description should contain the following:

          ```
          I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

          ## Summary

          Summary about this PR

          Close #issue
          ```

  # Check if PR description contain CLA
  - name: CLA Check
    conditions:
      - or:
          - author=Mergify
          - and:
              - 'body~=I hereby agree to the terms of the CLA available at: https:\/\/databend\.rs\/dev\/policies\/cla\/'
              - "body~=Summary"
    actions:
      post_check:
        title: |
          {% if check_succeed %}
          Description contains CLA
          {% else %}
          Description doesn't contain CLA
          {% endif %}
        summary: |
          {% if not check_succeed %}
          Pull request description must contain [CLA](https://databend.rs/doc/contributing/good-pr) like the following:

          ```
          I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

          ## Summary

          Summary about this PR

          Close #issue
          ```
          {% endif %}

  # Check if PR title contain valid types
  - name: Comment PR if title not semantic
    conditions:
      - author!=Mergify
      - -draft
      - '-title~=^(feat|fix|refactor|ci|build|docs|website|chore)(\(.*\))?:'
    actions:
      comment:
        message: |
          This pull request's title is not fulfill the requirements. @{{author}} please update it 🙏.

          Valid format:

          ```
          fix(query): fix group by string bug
            ^         ^---------------------^
            |         |
            |         +-> Summary in present tense.
            |
            +-------> Type: feat, fix, refactor, ci, build, docs, website, chore
          ```

          Valid types:

          - `feat`: this PR introduces a new feature to the codebase
          - `fix`: this PR patches a bug in codebase
          - `refactor`: this PR changes the code base without new features or bugfix
          - `ci|build`: this PR changes build/testing/ci steps
          - `docs|website`: this PR changes the documents or websites
          - `chore`: this PR only has small changes that no need to record

  # Check if PR title contain valid types
  - name: Semantic PR Check
    conditions:
      - or:
          - author=Mergify
          - 'title~=^(feat|fix|refactor|ci|build|docs|website|chore)(\(.*\))?:'
    actions:
      post_check:
        title: |
          {% if check_succeed %}
          Title follows Semantic PR
          {% else %}
          Title does not follow Semantic PR
          {% endif %}
        summary: |
          {% if not check_succeed %}
          Pull request title must follow [Semantic PR](https://databend.rs/doc/contributing/good-pr)

          Valid format:

          ```
          fix(query): fix group by string bug
            ^         ^---------------------^
            |         |
            |         +-> Summary in present tense.
            |
            +-------> Type: feat, fix, refactor, ci, build, docs, website, chore
          ```

          Valid types:

          - `feat`: this PR introduces a new feature to the codebase
          - `fix`: this PR patches a bug in codebase
          - `refactor`: this PR changes the code base without new features or bugfix
          - `ci|build`: this PR changes build/testing/ci steps
          - `docs|website`: this PR changes the documents or websites
          - `chore`: this PR only has small changes that no need to record
          {% endif %}

  # Assign pr label based of tags
  - name: label on New Feature
    conditions:
      - 'title~=^(feat)(\(.*\))?:'
    actions:
      label:
        add:
          - pr-feature
  - name: label on Bug Fix
    conditions:
      - 'title~=^(fix)(\(.*\))?:'
    actions:
      label:
        add:
          - pr-bugfix
  - name: label on Refactor
    conditions:
      - 'title~=^(refactor)(\(.*\))?:'
    actions:
      label:
        add:
          - pr-refactor
  - name: label on Build/Testing/CI
    conditions:
      - 'title~=^(ci|build)(\(.*\))?:'
    actions:
      label:
        add:
          - pr-build
  - name: label on Documentation
    conditions:
      - 'title~=^(docs|website)(\(.*\))?:'
    actions:
      label:
        add:
          - pr-doc
  - name: label on Not for changelog
    conditions:
      - 'title~=^(chore)(\(.*\))?:'
    actions:
      label:
        add:
          - pr-chore
