[package]
name = "common-meta-types"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[dependencies]
common-datavalues = { path = "../../datavalues" }
common-exception = { path = "../../exception" }
common-storage = { path = "../../storage" }

openraft = { git = "https://github.com/datafuselabs/openraft", rev = "v0.7.0-alpha.2" }
sled = { git = "https://github.com/datafuse-extras/sled", tag = "v0.34.7-datafuse.1", default-features = false }

anyerror = "0.1.6"
derive_more = "0.99.17"
enumflags2 = { version = "0.7.5", features = ["serde"] }
hex = "0.4.3"
maplit = "1.0.2"
num-derive = "0.3.3"
num-traits = "0.2.15"
once_cell = "1.12.0"
prost = "0.10.4"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
sha1 = "0.10.1"
sha2 = "0.10.2"
thiserror = "1.0.31"
tonic = { version = "0.7.2", features = ["transport", "codegen", "prost", "tls-roots", "tls"] }

[build-dependencies]
common-building = { path = "../../building" }
prost-build = "0.10.4"
tonic-build = "0.7.2"

[dev-dependencies]
anyhow = "1.0.58"
regex = "1.5.6"
