[package]
name = "databend-fuzz"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "fuzz_parse_sql"
path = "fuzz_targets/fuzz_parse_sql.rs"
doctest = false
test = false

[dependencies]
common-ast = { path = "../../common/ast" }

afl = "0.12"
arbitrary = "1.1.3"

[patch.crates-io]
parquet2 = { version = "0.14.1", optional = true, git = "https://github.com/datafuse-extras/parquet2", rev = "3a468fc3c4" }
chrono = { git = "https://github.com/datafuse-extras/chrono", rev = "279f590" }
