name: "Check"
description: "Check will do all essential checks"
inputs:
  github_token:
    description: "Github Token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Build Tool
      uses: ./.github/actions/setup_build_tool
      with:
        bypass_env_vars: RUSTFLAGS,RUST_LOG,GITHUB_TOKEN

    - name: Check License Header
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: make check-license

    - name: YAML Lint
      shell: bash
      run: make lint-yaml

    - name: Format
      shell: bash
      run: cargo fmt --all -- --check

    - name: Clippy
      shell: bash
      run: cargo -Z sparse-registry clippy --workspace --all-targets -- -D warnings

    - name: Audit dependencies
      shell: bash
      if: "!contains(github.event.head_commit.message, 'skip audit')"
      run: cargo -Z sparse-registry audit --db ./target/advisory-db

    - name: Check udeps
      shell: bash
      if: "!contains(github.event.head_commit.message, 'skip udeps')"
      run: cargo -Z sparse-registry udeps --workspace

    - name: Check toml format
      shell: bash
      run: taplo fmt --check
