name: "Check"
description: "Check will do all essential checks"
inputs:
  github_token:
    description: "Github Token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Build Tool
      uses: ./.github/actions/setup_build_tool

    # If you need to reset the cache version, increment the number after `v`
    - uses: Swatinem/rust-cache@v1
      with:
        sharedKey: base-v2

    - name: Check License Header
      uses: apache/skywalking-eyes@v0.2.0
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        log: info

    - name: YAML Lint
      uses: ibiqlik/action-yamllint@v3
      with:
        file_or_dir: ./
        config_file: .yamllint.yml

    - name: Format
      shell: bash
      run: cargo fmt --all -- --check

    - name: Clippy
      shell: bash
      run: cargo clippy --all -- -D warnings

    - name: Audit dependencies
      shell: bash
      if: "!contains(github.event.head_commit.message, 'skip audit')"
      run: cargo audit --db ./target/advisory-db

    - name: Check udeps
      shell: bash
      if: "!contains(github.event.head_commit.message, 'skip udeps')"
      run: cargo udeps --workspace

    - name: Check toml format
      shell: bash
      run: build-tool taplo fmt --check

    # for cache
    - shell: bash
      run: cargo metadata --all-features --format-version 1 > ./target/metadata.json
