[package]
name = "common-grpc"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[dependencies] # In alphabetical order
# Workspace dependencies
common-base = { path = "../base" }
common-exception = { path = "../exception" }
common-tracing = { path = "../tracing" }

# Github dependencies

# Crates.io dependencies
anyerror = "0.1.6"
hyper = "0.14.19"
jwt-simple = "0.11.0"
once_cell = "1.12.0"
serde = { version = "1.0.137", features = ["derive"] }
thiserror = "1.0.31"
tonic = { version = "0.7.2", features = ["transport", "codegen", "prost", "tls-roots", "tls"] }
trust-dns-resolver = { version = "0.21.2", features = ["system-config"] }

[build-dependencies]

[features]
mocks = []
