[package]
name = "common-datavalues"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[dependencies] # In alphabetical order
# Workspace dependencies
common-arrow = { path = "../arrow" }
common-exception = { path = "../exception" }
common-io = { path = "../io" }
primitive-types = "0.11.1"

# Github dependencies

# Crates.io dependencies
chrono = "0.4.19"
chrono-tz = "0.6.1"
dyn-clone = "1.0.6"
enum_dispatch = "0.3.8"
itertools = "0.10.3"
lexical-core = "0.8.5"
micromarshal = "0.1.0"
num = "0.4.0"
once_cell = "1.12.0"
opensrv-clickhouse = "0.1.0"
ordered-float = "3.0.0"
paste = "1.0.7"
rand = { version = "0.8.5", features = ["small_rng"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
smallvec = { version = "1.8.0", features = ["write"] }

[dev-dependencies]
criterion = "0.3.5"
pretty_assertions = "1.2.1"
rand = "0.8.5"

[[bench]]
name = "builder"
harness = false

[[bench]]
name = "if_else_then"
harness = false

[[bench]]
name = "eq"
harness = false

[[bench]]
name = "data_type"
harness = false

[[bench]]
name = "output_format"
harness = false
