[package]
name = "common-http"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false
test = false

[features]
memory-profiling = ["tempfile"]

[dependencies]
# Workspace dependencies
common-base = { path = "../base" }
common-exception = { path = "../exception" }

# Github dependencies

# Crates.io dependencies
futures = "0.3.21"
poem = { version = "1.3.31", features = ["rustls"] }
serde = { version = "1.0.137", features = ["derive"] }
tempfile = { version = "3.3.0", optional = true }
tracing = "0.1.35"

[dev-dependencies]
pretty_assertions = "1.2.1"
