[package]
name = "common-expression"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
test = false

[dependencies] # In alphabetical order
# Workspace dependencies
common-arrow = { path = "../arrow" }

# Github dependencies

# Crates.io dependencies
chrono-tz = "0.6.1"
comfy-table = "6"
enum-as-inner = "0.4"
itertools = "0.10"
match-template = "0.0.1"
num-traits = "0.2"
ordered-float = "1.0"
serde = "1.0"

[dev-dependencies]
common-ast = { path = "../ast" }
goldenfile = "1.4"
