[package]
name = "common-protos"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[dependencies]
num-derive = "0.3.3"
num-traits = "0.2.15"
prost = "0.10.4"
tonic = { version = "0.7.2", features = ["transport", "codegen", "prost", "tls-roots", "tls"] }

[build-dependencies]
prost-build = "0.10.4"
tonic-build = "0.7.2"

[dev-dependencies]
