[package]
name = "common-io"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false
test = false

[dependencies]
# Workspace dependencies
common-exception = { path = "../exception" }

# Github dependencies
bincode = { git = "https://github.com/datafuse-extras/bincode", rev = "fd3f9ff" }

# Crates.io dependencies
bytes = "1.1.0"
chrono = "0.4.19"
chrono-tz = "0.6.1"
futures = "0.3.21"
lexical-core = "0.8.5"
micromarshal = "0.1.0"
serde = { version = "1.0.137", features = ["derive"] }
time = "0.3.10"

[dev-dependencies]
rand = "0.8.5"
