[package]
name = "databend-metactl"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "databend-metactl"
doctest = false
test = false

[features]
io-uring = [
    "common-meta-sled-store/io-uring",
    "common-meta-raft-store/io-uring",
    "databend-meta/io-uring",
]

[dependencies]
# Workspace dependencies
common-base = { path = "../../common/base" }
common-meta-api = { path = "../../common/meta/api" }
common-meta-grpc = { path = "../../common/meta/grpc" }
common-meta-raft-store = { path = "../../common/meta/raft-store" }
common-meta-sled-store = { path = "../../common/meta/sled-store" }
common-meta-types = { path = "../../common/meta/types" }
common-tracing = { path = "../../common/tracing" }
databend-meta = { path = "../../metasrv" }
openraft = { git = "https://github.com/datafuselabs/openraft", rev = "v0.7.0-alpha.2" }

# Crates.io dependencies
anyhow = "1.0.58"
clap = { version = "3.2.5", features = ["derive", "env"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
tokio-stream = "0.1.9"
tonic = "0.7.2"
url = "2.2.2"
