name: "(hive) Test Stateful Standalone"
description: "(hive) Running stateful tests in standalone mode"
inputs:
  profile:
    description: "The profile for this test"
    required: true
    default: "debug"
  target:
    description: ""
    required: true
    default: "x86_64-unknown-linux-gnu"
runs:
  using: "composite"
  steps:
    - name: Download artifact
      uses: ./.github/actions/artifact_download
      with:
        profile: ${{ inputs.profile }}
        sha: ${{ github.sha }}
        target: ${{ inputs.target }}
        category: hive

    - name: Checkout java env
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: "11"

    # hive cluster setup
    - name: Hive Cluster Setup
      shell: bash
      run: |
        docker-compose -f "./docker/it-hive/hive-docker-compose.yml" up -d

    # Wait for h2 to come alive
    #  INSIDE the container of service "hive-server", wait for port 10000 being listened:
    #  - check if port 10000 is available, per sec
    #  - failed if not available during 50s (typically, service will be brought up in about 30s, in github)
    - name: Wait for hiveserver2
      shell: bash
      run: |
        docker-compose -f "./docker/it-hive/hive-docker-compose.yml" exec -T hive-server bash -c "timeout 50 bash -c 'until nc -z localhost 10000; do sleep 1; echo "waiting..."; done'"

    # hive test data setup, to be refined
    # hasn't find a way to read hdfs data from docker isolated network yet, use local fs not hdfs to do the ci
    # hive data is loaded to hdfs://namenode:8020/user/hive/warehouse/t_1/,  we copy a mirror data to local fs .databend/stateless_test_data/user/hive/warehouse/t_1/
    # databend actually read data from local fs
    - name: Hive Create Table&Load Data
      shell: bash
      run: |
        docker-compose -f "./docker/it-hive/hive-docker-compose.yml" exec -T hive-server bash -c "/opt/hive/bin/beeline -u jdbc:hive2://127.0.0.1:10000 -e 'CREATE TABLE t_1 (lo_orderkey integer, lo_orderpriority varchar(15)) stored as parquet;'"
        docker-compose -f "./docker/it-hive/hive-docker-compose.yml" exec -T hive-server bash -c "/opt/hive/bin/beeline -u jdbc:hive2://127.0.0.1:10000 -e 'load data local inpath \"/databend-data/t_1.parquet\" OVERWRITE into table t_1;'"
        mkdir -p .databend/stateless_test_data/user/hive/warehouse/t_1/
        cp tests/data/hive/t_1.parquet .databend/stateless_test_data/user/hive/warehouse/t_1/

    - name: Run Stateful Tests with Standalone mode
      shell: bash
      env:
        LD_LIBRARY_PATH: ${{ env.JAVA_HOME }}/lib/server:${{ env.LD_LIBRARY_PATH }}
      run: |
        bash ./scripts/ci/ci-run-stateful-hive-tests-standalone-embed-meta.sh

    - name: Stop containers
      if: always()
      shell: bash
      run: docker-compose -f "./docker/it-hive/hive-docker-compose.yml" down
