[package]
name = "common-meta-embedded"
version = "0.1.0"
description = "distributed meta data service"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[dependencies]
# Workspace dependencies
common-base = { path = "../../base" }
common-exception = { path = "../../exception" }
common-meta-api = { path = "../api" }
common-meta-raft-store = { path = "../raft-store" }
common-meta-sled-store = { path = "../sled-store" }
common-meta-types = { path = "../types" }
common-tracing = { path = "../../tracing" }

# Crates.io dependencies
async-trait = "0.1.56"
once_cell = "1.12.0"
tempfile = "3.3.0"

[dev-dependencies]
anyhow = "1.0.58"
