name: Dev Linux

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "website/**"
      - "**.md"
      - "scripts/setup/**"
      - "docker/**"
      - ".devcontainer/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

env:
  BUILD_PROFILE: debug

jobs:
  check:
    runs-on: [self-hosted, X64, Linux]
    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all tags,  metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/check
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build_gnu:
    name: build_${{ matrix.arch }}_gnu
    runs-on: [self-hosted, X64, Linux, development]
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all tags,  metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/build_linux
        with:
          target: ${{ matrix.arch }}-unknown-linux-gnu
          profile: debug

  build_musl:
    name: build_${{ matrix.arch }}_musl
    runs-on: [self-hosted, X64, Linux, development]
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all tags,  metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/build_linux
        with:
          target: ${{ matrix.arch }}-unknown-linux-musl
          profile: debug

  test_unit:
    runs-on: [self-hosted, X64, Linux]
    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all tags,  metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/test_unit
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

  test_metactl:
    runs-on: [self-hosted, X64, Linux, development]
    needs: build_gnu
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_metactl

  test_compat:
    runs-on: [self-hosted, X64, Linux, development]
    needs: build_gnu
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_compat

  test_meta_cluster:
    runs-on: [self-hosted, X64, Linux, development]
    needs: build_gnu
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_meta_cluster

  test_stateless_standalone_linux:
    runs-on: [self-hosted, X64, Linux, development]
    needs: build_gnu
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateless_standalone_linux

  test_stateless_cluster_linux:
    runs-on: [self-hosted, X64, Linux, development]
    needs: build_gnu
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateless_cluster_linux

  test_sqllogic_standalone_linux:
    runs-on: [self-hosted, X64, Linux, development]
    needs: build_gnu
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_sqllogic_standalone_linux

  test_stateful_standalone_linux:
    runs-on: [self-hosted, X64, Linux, development]
    needs: build_gnu
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateful_standalone_linux

  test_fuzz_standalone_linux:
    runs-on: [self-hosted, X64, Linux, development]
    needs: build_gnu
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_fuzz_standalone_linux
        continue-on-error: true

  build_hive:
    runs-on: [self-hosted, X64, Linux, development]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build_linux_hive
        with:
          target: x86_64-unknown-linux-gnu
          profile: debug

  test_stateful_hive_standalone:
    runs-on: [self-hosted, X64, Linux, development]
    needs: build_hive
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateful_hive_standalone
        with:
          target: x86_64-unknown-linux-gnu
          profile: debug
