name: Developing

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - 'docs/**'
      - 'website/**'
      - '**.md'
      - 'scripts/setup/**'
      - '.devcontainer/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'website/**'
      - '**.md'
      - 'scripts/setup/**'
      - '.devcontainer/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  PROTOC: protoc

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/check
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build_macos:
    runs-on: macos-11
    needs: check
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build_debug
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target: ${{ matrix.target }}

  build_linux:
    runs-on: ubuntu-latest
    needs: check
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build_debug
        with:
          target: ${{ matrix.target }}

  test_unit:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test_unit
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

  test_metactl:
    runs-on: ubuntu-latest
    needs: build_linux
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test_metactl

  test_compat:
    runs-on: ubuntu-latest
    needs: build_linux
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test_compat

  test_stateless_standalone_linux:
    runs-on: ubuntu-latest
    needs: build_linux
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test_stateless_standalone_linux

  # https://github.com/datafuselabs/databend/issues/5287
  #test_stateless_standalone_macos:
  #  runs-on: macos-11
  #  needs: build_macos
  #  steps:
  #    - uses: actions/checkout@v2
  #    - uses: ./.github/actions/test_stateless_standalone_macos

  test_stateless_cluster_linux:
    runs-on: ubuntu-latest
    needs: build_linux
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test_stateless_cluster_linux

  test_stateless_cluster_macos:
    runs-on: macos-11
    needs: build_macos
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test_stateless_cluster_macos

  test_stateful_standalone:
    runs-on: ubuntu-latest
    needs: build_linux
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test_stateful_standalone

  test_stateful_hive_standalone:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test_stateful_hive_standalone
